In [47]:
import pandas as pd
import geopandas as gpd
import numpy as np

In [48]:
cmap = pd.read_csv('data/community_area/2014_2018.csv')
cmap.columns = cmap.columns.str.lower()
cmap["geog"] = cmap["geog"].str.lower()

cmap["geog"] = cmap["geog"].str.replace("'", '')
cmap["geog"] = np.where(cmap.geog == "the loop", "loop", cmap.geog)

cmap.head(5)

,geog,tot_pop,und19,a20_34,a35_49,a50_64,a65_74,a75_84,ov85,pop_25ov,...,inc_50_75k,inc_75_100k,inc_100_150k,inc_gt_150,medinc,ct_1phh,ct_2phh,ct_3phh,ct_4mphh,hu_tot
0,albany park,50342.99998,12924.999990,12891.999990,11619.999990,8083.999996,2716.999999,1491.999999,613.000000,33611.999980,...,3056.000001,2124.000001,2522.000001,1989.000001,59883.04094,4227.000001,4495.000001,3088.000001,4868.000002,18447.000000
1,archer heights,13055.08151,4180.292247,2753.618290,2815.956263,1672.978132,985.051690,400.184891,247.000000,7987.638172,...,736.901785,338.959821,517.544643,146.772321,44108.84007,921.593749,853.741071,622.075893,1532.575892,4358.100203
2,armour square,13779.11840,2542.408010,2788.930936,2297.106212,2520.154383,1922.259432,1163.746373,544.513059,10443.911790,...,616.944954,346.155963,490.614679,237.912844,27463.83031,1772.564221,1784.701836,809.587156,1101.050459,5822.586737
3,ashburn,43985.99999,12981.000000,8464.999998,9192.999998,8529.999996,3057.000000,1147.000000,613.000001,27546.999990,...,2911.000000,2091.999998,2298.000001,1387.000000,68463.73500,2539.000000,3210.000001,2528.000000,4803.000000,13728.000010
4,auburn gresham,45271.00001,11183.000000,8665.000001,7891.000000,9595.000003,3860.000001,3204.000000,873.000000,31178.000010,...,2877.999998,1388.999998,1236.999999,547.999999,34661.22650,6218.999995,4775.999996,2562.999998,3408.999998,20726.000000

In [49]:
cmap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 50 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   geog          77 non-null     object
 1   tot_pop       77 non-null     float64
 2   und19         77 non-null     float64
 3   a20_34        77 non-null     float64
 4   a35_49        77 non-null     float64
 5   a50_64        77 non-null     float64
 6   a65_74        77 non-null     float64
 7   a75_84        77 non-null     float64
 8   ov85          77 non-null     float64
 9   pop_25ov      77 non-null     float64
 10  med_age       77 non-null     float64
 11  white         77 non-null     float64
 12  hisp          77 non-null     float64
 13  black         77 non-null     float64
 14  asian         77 non-null     float64
 15  other         77 non-null     float64
 16  in_lbfrc      77 non-null     float64
 17  emp           77 non-null     float64
 18  unemp         77 non-null     float64
 19  not_in_lbfrc  77 non-null     float64
 20  work_at_home  77 non-null     float64
 21  tot_comm      77 non-null     float64
 22  drove_al      77 non-null     float64
 23  carpool       77 non-null     float64
 24  transit       77 non-null     float64
 25  walk_bike     77 non-null     float64
 26  comm_other    77 non-null     float64
 27  agg_tt        77 non-null     float64
 28  no_veh        77 non-null     float64
 29  one_veh       77 non-null     float64
 30  two_veh       77 non-null     float64
 31  threeom_veh   77 non-null     float64
 32  lt_hs         77 non-null     float64
 33  hs            77 non-null     float64
 34  some_coll     77 non-null     float64
 35  assoc         77 non-null     float64
 36  bach          77 non-null     float64
 37  grad_prof     77 non-null     float64
 38  inc_lt_25k    77 non-null     float64
 39  inc_25_50k    77 non-null     float64
 40  inc_50_75k    77 non-null     float64
 41  inc_75_100k   77 non-null     float64
 42  inc_100_150k  77 non-null     float64
 43  inc_gt_150    77 non-null     float64
 44  medinc        77 non-null     float64
 45  ct_1phh       77 non-null     float64
 46  ct_2phh       77 non-null     float64
 47  ct_3phh       77 non-null     float64
 48  ct_4mphh      77 non-null     float64
 49  hu_tot        77 non-null     float64
dtypes: float64(49), object(1)
memory usage: 30.2+ KB

In [50]:
com_boundaries = gpd.read_file("data/community_area/com_boundaries.geojson")
com_boundaries["community"] = com_boundaries["community"].str.lower()
com_boundaries = com_boundaries.drop(['area', 'shape_area', 'perimeter', 
                                      'area_num_1', 'comarea_id', 'comarea', 
                                      'shape_len'], axis=1)
com_boundaries.columns = ['geog', 'area_num', 'geometry']
com_names = set(com_boundaries.geog)
cmap_names = set(cmap.geog)

# Checking for naming differences
print(cmap_names.difference(com_names))

set()

In [51]:
# Creating new features

cmap["perc_white"] = (cmap["white"] / cmap["tot_pop"]) * 100
cmap["perc_black"] = (cmap["black"] / cmap["tot_pop"]) * 100
cmap["perc_asian"] = (cmap["asian"] / cmap["tot_pop"]) * 100
cmap["perc_hisp"] = (cmap["hisp"] / cmap["tot_pop"]) * 100
cmap["perc_other_race"] = (cmap["other"] / cmap["tot_pop"]) * 100
cmap["perc_und19"] = (cmap["und19"] / cmap["tot_pop"]) * 100
cmap["perc_a20_34"] = (cmap["a20_34"] / cmap["tot_pop"]) * 100
cmap["perc_a35_49"] = (cmap["a35_49"] / cmap["tot_pop"]) * 100
cmap["perc_a50_64"] = (cmap["a50_64"] / cmap["tot_pop"]) * 100
cmap["perc_a65_74"] = (cmap["a65_74"] / cmap["tot_pop"]) * 100
cmap["perc_a75_84"] = (cmap["a75_84"] / cmap["tot_pop"]) * 100
cmap["perc_ov85"] = (cmap["ov85"] / cmap["tot_pop"]) * 100
cmap["perc_in_lbfrc"] = (cmap["in_lbfrc"] / cmap["tot_pop"]) * 100
cmap["perc_emp"] = (cmap["emp"] / cmap["tot_pop"]) * 100
cmap["perc_unemp"] = (cmap["unemp"] / cmap["tot_pop"]) * 100
cmap["perc_not_in_lbfrc"] = (cmap["not_in_lbfrc"] / cmap["tot_pop"]) * 100
cmap["perc_work_at_home"] = (cmap["work_at_home"] / cmap["tot_pop"]) * 100
cmap["perc_tot_comm"] = (cmap["tot_comm"] / cmap["tot_pop"]) * 100
cmap["perc_drove_al"] = (cmap["drove_al"] / cmap["tot_pop"]) * 100
cmap["perc_carpool"] = (cmap["carpool"] / cmap["tot_pop"]) * 100
cmap["perc_transit"] = (cmap["transit"] / cmap["tot_pop"]) * 100
cmap["perc_walk_bike"] = (cmap["walk_bike"] / cmap["tot_pop"]) * 100
cmap["perc_comm_other"] = (cmap["comm_other"] / cmap["tot_pop"]) * 100
cmap["agg_tt_avg"] = (cmap["agg_tt"] / cmap["emp"]) * 100
cmap["perc_lt_hs"] = (cmap["lt_hs"] / cmap["pop_25ov"]) * 100
cmap["perc_hs"] = (cmap["hs"] / cmap["pop_25ov"]) * 100
cmap["perc_some_coll"] = (cmap["some_coll"] / cmap["pop_25ov"]) * 100
cmap["perc_assoc"] = (cmap["assoc"] / cmap["pop_25ov"]) * 100
cmap["perc_bach"] = (cmap["bach"] / cmap["pop_25ov"]) * 100
cmap["perc_grad_prof"] = (cmap["grad_prof"] / cmap["pop_25ov"]) * 100
cmap["perc_ct_1phh"] = (cmap["ct_1phh"] / (cmap["ct_1phh"]+cmap["ct_2phh"]+cmap["ct_3phh"]+cmap["ct_4mphh"])) * 100
cmap["perc_ct_2phh"] = (cmap["ct_2phh"] / (cmap["ct_1phh"]+cmap["ct_2phh"]+cmap["ct_3phh"]+cmap["ct_4mphh"])) * 100
cmap["perc_ct_3phh"] = (cmap["ct_3phh"] / (cmap["ct_1phh"]+cmap["ct_2phh"]+cmap["ct_3phh"]+cmap["ct_4mphh"])) * 100
cmap["perc_ct_4mphh"] = (cmap["ct_4mphh"] /(cmap["ct_1phh"]+cmap["ct_2phh"]+cmap["ct_3phh"]+cmap["ct_4mphh"])) * 100

In [52]:
to_drop = ['tot_pop', 'und19', 'a20_34', 'a35_49', 'a50_64', 'a65_74',
           'a75_84', 'ov85', 'pop_25ov', 'white', 'hisp', 'black',
           'asian', 'other', 'in_lbfrc', 'emp', 'unemp', 'not_in_lbfrc',
           'work_at_home', 'tot_comm', 'drove_al', 'carpool', 'transit',
           'walk_bike', 'comm_other', 'no_veh', 'one_veh', 'two_veh',
           'threeom_veh', 'lt_hs', 'hs', 'some_coll', 'assoc', 'bach', 'grad_prof',
           'inc_lt_25k', 'inc_25_50k', 'inc_50_75k', 'inc_75_100k', 'inc_100_150k',
           'inc_gt_150', 'ct_1phh', 'ct_2phh', 'ct_3phh', 'ct_4mphh', 'hu_tot', 'agg_tt']
# Remove two columns name is 'C' and 'D'
cmap = cmap.drop(to_drop, axis = 1)

In [53]:
cmap.describe()

,med_age,medinc,perc_white,perc_black,perc_asian,perc_hisp,perc_other_race,perc_und19,perc_a20_34,perc_a35_49,...,perc_lt_hs,perc_hs,perc_some_coll,perc_assoc,perc_bach,perc_grad_prof,perc_ct_1phh,perc_ct_2phh,perc_ct_3phh,perc_ct_4mphh
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,...,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,36.055568,53334.505367,27.804544,37.901289,6.181272,26.221450,1.891445,24.732435,24.741161,19.632570,...,16.552511,25.714572,19.823506,6.173357,18.776279,12.959775,34.593369,28.077733,14.839357,22.489541
std,5.009337,25339.046908,27.048999,39.495515,10.680467,28.058186,1.293513,6.502553,7.676986,2.674448,...,9.880902,10.272380,6.943268,1.872738,11.417289,11.160655,10.908262,4.890754,3.242938,10.748535
min,23.013966,13517.699120,0.428082,0.753287,0.000000,0.564814,0.000000,8.877160,13.847434,14.083338,...,1.393631,3.647829,6.355567,1.785641,2.209782,1.495536,16.050272,15.877551,5.395001,2.596333
25%,32.130013,33419.903970,3.503644,3.067584,0.362477,4.255326,0.900557,20.192196,19.495937,17.597478,...,10.140338,19.663321,14.570228,4.829643,9.923843,5.103385,26.087806,24.356887,13.340935,13.771518
50%,35.421417,48966.666670,14.792442,13.484269,2.031028,13.591060,1.622983,25.314746,22.763954,19.630212,...,14.481969,26.222295,19.148690,6.063650,14.690195,9.023482,32.078371,28.148759,15.168806,22.244990
75%,39.116321,66309.308350,47.962158,87.389969,8.036686,45.658781,2.712749,29.511663,26.150231,21.514680,...,21.556614,33.040331,24.913770,7.570594,25.698362,17.558094,44.636453,31.505826,17.028569,28.303492
max,50.523175,115756.172800,84.257057,96.960616,72.774081,91.781589,4.975782,43.321399,49.000965,28.077300,...,47.837832,46.581933,41.101945,10.398929,47.854759,50.228964,58.048632,40.256424,20.052715,49.724490

In [54]:
final_com = pd.merge(com_boundaries, cmap, on='geog')

In [55]:
final_com.to_file("data/community_area/com_cmap.shp")

<ipython-input-55-19041a190018>:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  final_com.to_file("data/community_area/com_cmap.shp")